version: '3.7'

services:
  minio:
    image: "minio/minio"
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"
    restart: always
    environment:
      MINIO_ROOT_USER: access-key
      MINIO_ROOT_PASSWORD: secret-key
    volumes:
      - C:\docker\data\minio:/data
